import type { Agent, LifecycleEvent } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "a1",
    name: "Orchestrator",
    role: "Mission Control",
    domain: "Management",
    skills: ["Planning", "Routing"],
    lifecycle: "persistent",
  },
  {
    id: "a2",
    name: "Frontend Lead",
    role: "UI Systems",
    parentId: "a1",
    domain: "Frontend",
    skills: ["React", "Design Systems"],
    lifecycle: "persistent",
    workspace: "Browser",
  },
  {
    id: "a3",
    name: "Backend Lead",
    role: "API Systems",
    parentId: "a1",
    domain: "Backend",
    skills: ["Node.js", "Contracts"],
    lifecycle: "persistent",
    workspace: "Postgres",
  },
  {
    id: "a4",
    name: "Research Scout",
    role: "Context Fetcher",
    parentId: "a3",
    domain: "Research",
    skills: ["Docs", "Tracing"],
    lifecycle: "ephemeral",
    workspace: "Notion",
  },
  {
    id: "a5",
    name: "Crash Analyzer",
    role: "Recovery Branch",
    parentId: "a2",
    domain: "Frontend",
    skills: ["Debugging", "Fallbacks"],
    lifecycle: "ephemeral",
    workspace: "Sentry",
  },
  {
    id: "a6",
    name: "QA Runner",
    role: "Regression Sweep",
    parentId: "a1",
    domain: "Testing",
    skills: ["E2E", "Verification"],
    lifecycle: "contract",
    workspace: "Staging",
  },
  {
    id: "a7",
    name: "Release Manager",
    role: "Launch Coordinator",
    parentId: "a1",
    domain: "Management",
    skills: ["Approvals", "Rollouts"],
    lifecycle: "contract",
    workspace: "GitHub",
  },
];

export const mockEvents: LifecycleEvent[] = [
  { id: "e1", agentId: "a1", timestamp: 0, type: "spawn" },
  { id: "e2", agentId: "a1", timestamp: 4, type: "start" },
  { id: "e3", agentId: "a1", timestamp: 14, type: "split", targetId: "a2" },
  { id: "e4", agentId: "a2", timestamp: 14, type: "spawn" },
  { id: "e5", agentId: "a1", timestamp: 18, type: "split", targetId: "a3" },
  { id: "e6", agentId: "a3", timestamp: 18, type: "spawn" },
  { id: "e7", agentId: "a2", timestamp: 20, type: "start" },
  { id: "e8", agentId: "a3", timestamp: 24, type: "start" },
  { id: "e9", agentId: "a3", timestamp: 52, type: "split", targetId: "a4" },
  { id: "e10", agentId: "a4", timestamp: 52, type: "spawn" },
  { id: "e11", agentId: "a4", timestamp: 58, type: "start" },
  { id: "e12", agentId: "a4", timestamp: 82, type: "merge", targetId: "a3" },
  { id: "e13", agentId: "a4", timestamp: 84, type: "archive" },
  { id: "e14", agentId: "a2", timestamp: 96, type: "pause", details: "Waiting on API contract" },
  { id: "e15", agentId: "a3", timestamp: 100, type: "handoff", targetId: "a2" },
  { id: "e16", agentId: "a2", timestamp: 104, type: "resume" },
  { id: "e17", agentId: "a2", timestamp: 118, type: "error", details: "Token refresh loop" },
  { id: "e18", agentId: "a2", timestamp: 124, type: "split", targetId: "a5" },
  { id: "e19", agentId: "a5", timestamp: 124, type: "spawn" },
  { id: "e20", agentId: "a5", timestamp: 130, type: "start" },
  { id: "e21", agentId: "a5", timestamp: 150, type: "merge", targetId: "a2" },
  { id: "e22", agentId: "a5", timestamp: 152, type: "archive" },
  { id: "e23", agentId: "a2", timestamp: 156, type: "resume" },
  { id: "e24", agentId: "a1", timestamp: 168, type: "split", targetId: "a6" },
  { id: "e25", agentId: "a6", timestamp: 168, type: "spawn" },
  { id: "e26", agentId: "a6", timestamp: 174, type: "start" },
  { id: "e27", agentId: "a6", timestamp: 196, type: "merge", targetId: "a1" },
  { id: "e28", agentId: "a6", timestamp: 198, type: "archive" },
  { id: "e29", agentId: "a1", timestamp: 206, type: "split", targetId: "a7" },
  { id: "e30", agentId: "a7", timestamp: 206, type: "spawn" },
  { id: "e31", agentId: "a7", timestamp: 212, type: "start" },
  { id: "e32", agentId: "a2", timestamp: 220, type: "pause", details: "Ready for release" },
  { id: "e33", agentId: "a3", timestamp: 220, type: "pause", details: "Ready for release" },
  { id: "e34", agentId: "a7", timestamp: 230, type: "merge", targetId: "a1" },
  { id: "e35", agentId: "a7", timestamp: 232, type: "archive" },
  { id: "e36", agentId: "a1", timestamp: 236, type: "pause", details: "Awaiting approval" },
];

export const mockTimelineEnd = 250;
